import {initializeApp} from 'firebase/app'
import {getAuth,GoogleAuthProvider,browserLocalPersistence,createUserWithEmailAndPassword,onAuthStateChanged,sendEmailVerification,sendPasswordResetEmail,setPersistence,signInWithEmailAndPassword,signInWithPopup,signOut,updateProfile,reload,applyActionCode,verifyPasswordResetCode,confirmPasswordReset} from 'firebase/auth'

const firebaseConfig={apiKey:'AIzaSyCeuizWkJRvp2_iOxD4UOFL12Os2k0KybQ',authDomain:'living-india-7f73b.firebaseapp.com',projectId:'living-india-7f73b',storageBucket:'living-india-7f73b.firebasestorage.app',messagingSenderId:'439601825953',appId:'1:439601825953:web:cc38c29d819b86de03c8e0',measurementId:'G-N76WYJXS7K'}
const auth=getAuth(initializeApp(firebaseConfig)),googleProvider=new GoogleAuthProvider()
setPersistence(auth,browserLocalPersistence).catch(()=>{})
const $=id=>document.getElementById(id),home=new URL('./',location.href).href,authUrl=new URL('./auth.html',location.href).href
let mode='signin',pendingEmail=sessionStorage.getItem('li-pending-email')||'',resetCode=''
const baseForm=$('form').innerHTML
function errorText(e){const m={'auth/invalid-credential':'Incorrect email or password.','auth/invalid-login-credentials':'Incorrect email or password.','auth/email-already-in-use':'An account with this email already exists. Please sign in.','auth/weak-password':'Password should be at least 6 characters.','auth/invalid-email':'Please enter a valid email address.','auth/popup-blocked':'Google sign-in was blocked. Allow pop-ups and try again.','auth/popup-closed-by-user':'Google sign-in was cancelled.','auth/network-request-failed':'Cannot reach the account service. Check your connection.','auth/too-many-requests':'Too many attempts. Please wait and try again.','auth/user-disabled':'This account has been disabled.','auth/operation-not-allowed':'This sign-in method is not enabled.','auth/unauthorized-domain':'This website domain is not authorised in Firebase.','auth/invalid-action-code':'This email link is invalid or expired.','auth/expired-action-code':'This email link has expired.','auth/user-not-found':'No account was found for that email.'};return m[e?.code]||e?.message||'Something went wrong. Please try again.'}
function status(text,ok=false){const e=$('status');if(e){e.textContent=text;e.className='status '+(ok?'ok':'')}}
function restoreForm(){if(!$('nameBox'))$('form').innerHTML=baseForm;$('showPass')?.addEventListener('click',togglePassword)}
function togglePassword(){const x=$('password');if(!x)return;x.type=x.type==='password'?'text':'password';document.querySelectorAll('.show').forEach(b=>b.textContent=x.type==='password'?'Show':'Hide')}
function links(){$('links')?.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>render(b.dataset.mode))}
function render(next){mode=next;const signup=next==='signup',reset=next==='reset',verify=next==='verify',recovery=next==='recovery';if(!verify&&!recovery)restoreForm();$('ey').textContent=recovery?'SECURE ACCOUNT':reset?'ACCOUNT RECOVERY':signup?'JOIN THE ARCHIVE':verify?'EMAIL VERIFICATION':'WELCOME BACK';$('title').textContent=recovery?'Choose a new password':reset?'Reset password':signup?'Create your account':verify?'Check your email':'Sign in';$('sub').textContent=recovery?'Enter a new password for your Living India account.':reset?'Enter your email and we will send a secure reset link.':signup?'Create an account and verify your email before entering Living India.':verify?'We sent a verification link to your email. Open it, then return here to sign in.':'Sign in to save discoveries, collect heritage stamps and share stories.';$('nameBox')?.classList.toggle('hidden',!signup);$('emailBox')?.classList.toggle('hidden',verify||recovery);$('passBox')?.classList.toggle('hidden',reset||verify||recovery);$('confirmBox')?.classList.toggle('hidden',!signup&&!recovery);$('google')?.classList.toggle('hidden',reset||verify||recovery);$('otpNote')?.classList.toggle('hidden',!verify);$('links').innerHTML=(reset||verify||recovery)?'<button type="button" data-mode="signin">Back to sign in</button>':signup?'<button type="button" data-mode="signin">Already have an account?</button>':'<button type="button" data-mode="signup">Create account</button><button type="button" data-mode="reset">Forgot password?</button>';links();if(verify){$('form').innerHTML='<label>EMAIL</label><input id="verifyEmail" type="email" readonly><button class="primary" id="verifyBtn" type="button">I have verified my email →</button><button class="secondary" id="resendBtn" type="button">Send verification reminder</button>';$('verifyEmail').value=pendingEmail;$('verifyBtn').onclick=()=>render('signin');$('resendBtn').onclick=()=>{render('signin');$('email').value=pendingEmail;status('Sign in with your password. If your email is still unverified, a fresh verification link will be sent automatically.')}}else if(recovery){$('form').innerHTML='<label>NEW PASSWORD</label><div class="pw"><input id="password" type="password" minlength="6" required autocomplete="new-password"><button class="show" id="showPass" type="button">Show</button></div><label>CONFIRM NEW PASSWORD</label><input id="confirm" type="password" minlength="6" required autocomplete="new-password"><button class="primary" id="submit" type="submit">Update password →</button>';$('showPass').onclick=togglePassword}else{$('submit').textContent=reset?'Send reset link →':signup?'Create account →':'Sign in →'}$('form').onsubmit=submit;status('')}
async function submit(e){e.preventDefault();const btn=$('submit')||$('verifyBtn');if(btn)btn.disabled=true;status('Connecting…');try{if(mode==='signin'){const c=await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);await reload(c.user);if(!c.user.emailVerified){pendingEmail=c.user.email||'';sessionStorage.setItem('li-pending-email',pendingEmail);await sendEmailVerification(c.user,{url:authUrl+'?verified=1',handleCodeInApp:true});await signOut(auth);render('verify');status('Your email is not verified yet. We sent a fresh verification link.',true);return}location.replace(home);return}if(mode==='signup'){const p=$('password').value;if(p!==$('confirm').value)throw new Error('Passwords do not match.');pendingEmail=$('email').value.trim();const c=await createUserWithEmailAndPassword(auth,pendingEmail,p);const name=$('name').value.trim();if(name)await updateProfile(c.user,{displayName:name});await sendEmailVerification(c.user,{url:authUrl+'?verified=1',handleCodeInApp:true});sessionStorage.setItem('li-pending-email',pendingEmail);await signOut(auth);render('verify');status('Verification email sent. Check Inbox, Spam and Promotions.',true);return}if(mode==='reset'){await sendPasswordResetEmail(auth,$('email').value.trim(),{url:authUrl,handleCodeInApp:true});status('Password reset email sent. Check your inbox.',true);return}if(mode==='recovery'){if(!resetCode)throw new Error('The password reset link is missing or invalid.');const p=$('password').value;if(p!==$('confirm').value)throw new Error('Passwords do not match.');await confirmPasswordReset(auth,resetCode,p);resetCode='';status('Password updated successfully. You can now sign in.',true);setTimeout(()=>render('signin'),700)}}catch(err){console.error('[Living India Auth]',err);status(errorText(err))}finally{if($('submit'))$('submit').disabled=false;if($('verifyBtn'))$('verifyBtn').disabled=false}}
async function googleLogin(){status('Opening Google sign-in…');try{const result=await signInWithPopup(auth,googleProvider);if(result?.user)location.replace(home)}catch(err){console.error('[Living India Google]',err);status(errorText(err))}}
$('back')?.addEventListener('click',()=>location.replace(home));$('showPass')?.addEventListener('click',togglePassword);$('googleBtn')?.addEventListener('click',googleLogin)
;(async()=>{const p=new URLSearchParams(location.search),oob=p.get('oobCode')||'',action=p.get('mode'),verified=p.get('verified')==='1';render(action==='signup'?'signup':'signin');try{if(oob&&action==='verifyEmail'){await applyActionCode(auth,oob);pendingEmail=sessionStorage.getItem('li-pending-email')||'';sessionStorage.removeItem('li-pending-email');render('signin');if(pendingEmail)$('email').value=pendingEmail;status('Email verified successfully. You can now sign in.',true);return}if(oob&&action==='resetPassword'){await verifyPasswordResetCode(auth,oob);resetCode=oob;render('recovery');status('Choose a new password.',true);return}if(verified){render('signin');if(pendingEmail)$('email').value=pendingEmail;status('Your verification link was opened. Sign in now to continue.',true);return}}catch(err){status(errorText(err));return}onAuthStateChanged(auth,async user=>{if(!user)return;try{await reload(user);if(user.providerData.some(p=>p.providerId==='google.com')||user.emailVerified)location.replace(home)}catch(err){console.error('[Living India Session]',err)}})})()
