/* Living India — Supabase Auth */
const SUPABASE_URL = "https://nbxxknkecpnscirfnov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_OxxgbDWRCVy3LPM69E_ydA_ybhkXURb";
const LIVING_INDIA_URL = "https://ghostblade7.github.io/Sih/";

let liSupabase=null,liMode="signin",liBusy=false,liOtpEmail="",liResetMode=false;
function liReady(){if(!window.supabase?.createClient){console.error("Living India: Supabase JS failed to load.");return false}if(!liSupabase)liSupabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);return true}
function liStyles(){if(document.getElementById("li-auth-styles"))return;const s=document.createElement("style");s.id="li-auth-styles";s.textContent=`#li-auth-root{position:fixed;inset:0;z-index:99999;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(10,27,27,.72);backdrop-filter:blur(8px)}#li-auth-root.open{display:flex}.li-auth-card{width:min(440px,100%);max-height:92vh;overflow:auto;background:#f8f2e6;border:1px solid rgba(188,146,74,.55);border-radius:22px;box-shadow:0 24px 80px rgba(0,0,0,.38);padding:30px;color:#173c3b;position:relative}.li-auth-close{position:absolute;right:14px;top:12px;border:0;background:transparent;font-size:25px;cursor:pointer;color:#173c3b}.li-auth-mark{text-align:center;font-size:27px}.li-auth-card h2{text-align:center;margin:8px 0 4px;font-family:Georgia,serif;font-size:29px}.li-auth-sub{text-align:center;color:#65706c;margin:0 0 22px;font-size:14px;line-height:1.4}.li-auth-card label{display:block;font-size:13px;font-weight:700;margin:13px 0 6px}.li-auth-card input{box-sizing:border-box;width:100%;padding:13px 14px;border:1px solid #cfc8b9;border-radius:11px;background:#fffdf8;font-size:15px;outline:none}.li-auth-card input:focus{border-color:#a47b38;box-shadow:0 0 0 3px rgba(164,123,56,.12)}.li-auth-submit{width:100%;margin-top:18px;padding:13px;border:0;border-radius:11px;background:#173c3b;color:#fff;font-weight:800;font-size:15px;cursor:pointer}.li-auth-submit:disabled{opacity:.6;cursor:wait}.li-auth-google{width:100%;margin-top:10px;padding:12px;border:1px solid #bcb5a7;border-radius:11px;background:#fff;color:#173c3b;font-weight:700;cursor:pointer}.li-auth-divider{display:flex;align-items:center;gap:10px;margin:17px 0;color:#888;font-size:12px}.li-auth-divider:before,.li-auth-divider:after{content:"";height:1px;background:#d7d0c3;flex:1}.li-auth-switch{text-align:center;margin:18px 0 0;font-size:13px;color:#65706c}.li-auth-switch button,.li-auth-forgot,.li-auth-back{border:0;background:none;color:#9a6e28;font-weight:800;cursor:pointer}.li-auth-forgot,.li-auth-back{display:block;margin:9px 0 0;padding:0;font-size:12px}.li-auth-msg{min-height:20px;margin-top:12px;text-align:center;font-size:13px;font-weight:700;line-height:1.4}.li-auth-user{position:fixed;right:18px;top:74px;z-index:9998;background:#f8f2e6;border:1px solid #d3c4a8;border-radius:12px;padding:9px 12px;display:none;box-shadow:0 8px 25px rgba(0,0,0,.18);color:#173c3b}.li-auth-user button{margin-left:10px;border:0;background:none;color:#9a6e28;font-weight:800;cursor:pointer}.li-otp{letter-spacing:7px;text-align:center;font-weight:800;font-size:20px}`;document.head.appendChild(s)}
function liMount(){liStyles();if(document.getElementById("li-auth-root"))return;const root=document.createElement("div");root.id="li-auth-root";root.innerHTML=`<div class="li-auth-card" role="dialog" aria-modal="true"><button class="li-auth-close" aria-label="Close">×</button><div class="li-auth-mark">✺</div><h2>Living India</h2><p class="li-auth-sub" id="li-auth-title"></p><div id="li-auth-fields"></div><button class="li-auth-submit" id="li-submit"></button><div id="li-auth-extra"></div><div class="li-auth-msg" id="li-msg"></div></div>`;document.body.appendChild(root);root.addEventListener("click",e=>{if(e.target===root||e.target.closest(".li-auth-close"))liClose()});}
function liRender(){const f=document.getElementById("li-auth-fields"),x=document.getElementById("li-auth-extra"),t=document.getElementById("li-auth-title"),b=document.getElementById("li-submit");if(liMode==="otp"){t.textContent=`We sent a 6-digit verification code to ${liOtpEmail}.`;f.innerHTML=`<label>Verification code</label><input id="li-otp" class="li-otp" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="123456">`;b.textContent="Verify Email";x.innerHTML=`<button class="li-auth-back" id="li-otp-back">Back to sign up</button>`;document.getElementById("li-otp-back").onclick=()=>{liMode="signup";liRender()};return}if(liMode==="reset"){t.textContent="Create a new password.";f.innerHTML=`<label>New password</label><input id="li-password" type="password" autocomplete="new-password" placeholder="At least 6 characters"><label>Confirm new password</label><input id="li-confirm" type="password" autocomplete="new-password" placeholder="Repeat your password">`;b.textContent="Update Password";x.innerHTML="";return}const signup=liMode==="signup";t.textContent=signup?"Create your account and start exploring.":"Welcome back — sign in to continue.";f.innerHTML=`${signup?'<label>Name</label><input id="li-name" type="text" autocomplete="name" placeholder="Your name">':''}<label>Email</label><input id="li-email" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="li-password" type="password" autocomplete="current-password" placeholder="At least 6 characters">${signup?'<label>Confirm password</label><input id="li-confirm" type="password" autocomplete="new-password" placeholder="Repeat your password">':''}`;b.textContent=signup?"Create Account":"Sign In";x.innerHTML=signup?`<div class="li-auth-divider">OR</div><button class="li-auth-google" id="li-google">Continue with Google</button><p class="li-auth-switch">Already have an account? <button id="li-switch">Sign in</button></p>`:`<button class="li-auth-forgot" id="li-forgot">Forgot password?</button><div class="li-auth-divider">OR</div><button class="li-auth-google" id="li-google">Continue with Google</button><p class="li-auth-switch">New to Living India? <button id="li-switch">Sign up</button></p>`;b.onclick=liSubmit;document.getElementById("li-google").onclick=liGoogle;document.getElementById("li-switch").onclick=()=>{liMode=signup?"signin":"signup";liRender()};document.getElementById("li-forgot")?.addEventListener("click",()=>{liForgot()});document.getElementById(signup?"li-name":"li-email")?.focus()}
function liOpen(mode="signin"){liMount();liMode=mode;liResetMode=false;liRender();document.getElementById("li-auth-root").classList.add("open")}
function liClose(){document.getElementById("li-auth-root")?.classList.remove("open")}
function liMsg(text,error=false){const el=document.getElementById("li-msg");if(el){el.textContent=text;el.style.color=error?"#a33d32":"#52725f"}}
function liBusySet(v){liBusy=v;const b=document.getElementById("li-submit"),g=document.getElementById("li-google");if(b)b.disabled=v;if(g)g.disabled=v}
async function liSubmit(){if(!liReady()||liBusy)return;const email=document.getElementById("li-email")?.value.trim(),password=document.getElementById("li-password")?.value||"";if(liMode==="otp"){const token=(document.getElementById("li-otp")?.value||"").replace(/\D/g,"");if(token.length!==6)return liMsg("Enter the 6-digit code from your email.",true);liBusySet(true);liMsg("Verifying your email…");try{const{error}=await liSupabase.auth.verifyOtp({email:liOtpEmail,token,type:"signup"});if(error)throw error;liMsg("Email verified! Welcome to Living India.");setTimeout(liClose,900)}catch(e){liMsg(e.message||"Invalid or expired code.",true)}finally{liBusySet(false)}return}if(liMode==="reset"){const confirm=document.getElementById("li-confirm")?.value||"";if(password.length<6)return liMsg("Password must be at least 6 characters.",true);if(password!==confirm)return liMsg("Passwords do not match.",true);liBusySet(true);try{const{error}=await liSupabase.auth.updateUser({password});if(error)throw error;liMsg("Password updated successfully.");setTimeout(liClose,900)}catch(e){liMsg(e.message||"Could not update password.",true)}finally{liBusySet(false)}return}const name=document.getElementById("li-name")?.value.trim()||"";if(!email||password.length<6)return liMsg("Enter a valid email and a password of at least 6 characters.",true);if(liMode==="signup"){const confirm=document.getElementById("li-confirm")?.value||"";if(!name)return liMsg("Please enter your name.",true);if(password!==confirm)return liMsg("Passwords do not match.",true)}liBusySet(true);liMsg(liMode==="signup"?"Creating your account…":"Signing you in…");try{if(liMode==="signup"){const{data,error}=await liSupabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:LIVING_INDIA_URL}});if(error)throw error;if(data.user){liOtpEmail=email;liMode="otp";liRender();liMsg("Check your email for the 6-digit code.")}}else{const{error}=await liSupabase.auth.signInWithPassword({email,password});if(error)throw error;liMsg("Signed in successfully!");setTimeout(liClose,700)}}catch(e){liMsg(e.message||"Authentication failed.",true)}finally{liBusySet(false)}}
async function liGoogle(){if(!liReady()||liBusy)return;liBusySet(true);liMsg("Opening Google…");try{const{error}=await liSupabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:LIVING_INDIA_URL}});if(error)throw error}catch(e){liMsg(e.message||"Google sign-in failed.",true);liBusySet(false)}}
async function liForgot(){if(!liReady())return;const email=document.getElementById("li-email")?.value.trim();if(!email)return liMsg("Enter your email first.",true);liBusySet(true);liMsg("Sending reset email…");try{const{error}=await liSupabase.auth.resetPasswordForEmail(email,{redirectTo:LIVING_INDIA_URL});if(error)throw error;liMsg("Password reset email sent. Check your inbox.")}catch(e){liMsg(e.message||"Could not send reset email.",true)}finally{liBusySet(false)}}
function liAuthListener(){if(!liReady())return;liSupabase.auth.onAuthStateChange((event,session)=>{const u=document.getElementById("li-auth-user");if(!u)return;if(session?.user){u.style.display="block";u.querySelector("span").textContent=session.user.user_metadata?.full_name||session.user.email||"Signed in"}else u.style.display="none"});liSupabase.auth.getSession().then(({data})=>{const u=document.getElementById("li-auth-user");if(u&&data.session){u.style.display="block";u.querySelector("span").textContent=data.session.user.user_metadata?.full_name||data.session.user.email||"Signed in"}})}
function liInterceptLogin(){document.addEventListener("click",e=>{const btn=e.target.closest("button");if(!btn)return;const text=(btn.textContent||"").trim();if(text==="Login"||text==="♙Login"){e.preventDefault();e.stopImmediatePropagation();liOpen("signin")}},true)}
function liRemoveDemoModal(){const all=document.querySelectorAll("body *");for(const el of all){if(el.id==="li-auth-root")continue;const text=(el.textContent||"").trim();if(text.includes("Demo Sign In")&&text.length<3000){const candidate=el.closest("[role=dialog]")||el.closest(".modal")||el.parentElement?.parentElement||el.parentElement;if(candidate&&candidate!==document.body){candidate.style.display="none";candidate.setAttribute("aria-hidden","true");liOpen("signin");return true}}}return false}
function liWatchDemoModal(){liRemoveDemoModal();new MutationObserver(()=>{if(!document.getElementById("li-auth-root")?.classList.contains("open"))liRemoveDemoModal()}).observe(document.body,{childList:true,subtree:true})}
window.LivingIndiaAuthOpen=liOpen;
window.addEventListener("DOMContentLoaded",()=>{liMount();const user=document.createElement("div");user.id="li-auth-user";user.className="li-auth-user";user.innerHTML='<span></span><button>Sign out</button>';document.body.appendChild(user);user.querySelector("button").onclick=async()=>{if(liReady())await liSupabase.auth.signOut();user.style.display="none"};liInterceptLogin();liAuthListener();liWatchDemoModal()});
