import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";
import "./ui-overrides.css";
import "./auth.js";
const API=import.meta.env.VITE_API_URL||"http://localhost:3001/api";
const IMG={harappa:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Harappa_Ruins_-_IV.jpg",madhubani:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Madhubani_painting.jpg",baul:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Baul_singer.jpg",kalamkari:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Kalamkari_painting.jpg",theyyam:"https://commons.wikimedia.org/wiki/Special:Redirect/file/The_Theyyam.jpg",pattachitra:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Pattachitra_painting.jpg"};
const heritage=[
{id:"madhubani",title:"Madhubani Painting",type:"Visual Art",place:"Bihar",period:"Living tradition",interest:"art",image:IMG.madhubani,icon:"◈",desc:"A vibrant Mithila painting tradition carried through homes, rituals and generations of artists.",facts:["Mithila motifs","Natural pigments","Women-led transmission","Ritual & everyday art"]},
{id:"baul",title:"Baul Music",type:"Folk Tradition",place:"West Bengal",period:"Living oral tradition",interest:"music",image:IMG.baul,icon:"♪",desc:"Songs, philosophy and travelling performance passed from voice to voice across Bengal.",facts:["Oral transmission","Ektara & instruments","Mystical poetry","Travelling performers"]},
{id:"kalamkari",title:"Kalamkari",type:"Textile Art",place:"Andhra Pradesh",period:"Living craft tradition",interest:"craft",image:IMG.kalamkari,icon:"✦",desc:"Hand-painted and block-printed textiles where dye, line and storytelling meet.",facts:["Hand drawing","Natural dyes","Block printing","Narrative textiles"]},
{id:"theyyam",title:"Theyyam",type:"Ritual Art",place:"Kerala",period:"Living ritual tradition",interest:"performance",image:IMG.theyyam,icon:"✺",desc:"A powerful ritual performance combining costume, dance, percussion and community memory.",facts:["Ritual performance","Elaborate costume","Percussion","Community participation"]},
{id:"pattachitra",title:"Pattachitra",type:"Visual Art",place:"Odisha",period:"Living craft tradition",interest:"art",image:IMG.pattachitra,icon:"❋",desc:"Narrative cloth painting with disciplined lines, traditional pigments and regional stories.",facts:["Cloth preparation","Traditional pigments","Narrative painting","Chitrakara communities"]},
{id:"harappa",title:"Harappa",type:"Ancient Civilization",place:"Indus Valley",period:"c. 2600–1900 BCE",interest:"history",image:IMG.harappa,icon:"🏺",desc:"An ancient urban centre remembered for planned streets, drainage, craft and long-distance trade.",facts:["Grid-planned streets","Advanced drainage","Craft workshops","Seals & trade"]}];
const riskItems=[["Baul Music","Declining number of practitioners",68,"High"],["Kani Tribal Language","At risk of extinction",52,"High"],["Kavadi Attam","Decreasing youth participation",71,"Medium"],["Bamboo Craft","Lack of market support",74,"Medium"]];
const states=[["Rajasthan","Desert crafts",23,18,"craft"],["Punjab","Harappa",38,23,"history"],["Bihar","Madhubani",53,34,"art"],["West Bengal","Baul",69,37,"music"],["Gujarat","Garba",35,43,"performance"],["Maharashtra","Warli",45,55,"art"],["Andhra Pradesh","Kalamkari",63,55,"craft"],["Odisha","Pattachitra",71,49,"art"],["Kerala","Theyyam",72,69,"performance"],["Tamil Nadu","Temple arts",55,72,"performance"]];
const experienceOptions=[["image","Interactive Explorer","Tap into artworks, artefacts and visual stories."],["timeline","Timeline","Drag through the journey from roots to today."],["process","How It’s Made","Explore traditional processes step by step."],["connections","Culture Connections","Follow links between food, art, rituals, places and people."],["surprise","You Might Be Surprised","Find small discoveries and interactive facts."],["quiz","Quiz & Challenge","Identify, answer and learn with lightweight challenges."],["audio","Listen & Explore","Hear music, instruments, languages and oral traditions."],["beforeafter","Before / After","Compare heritage across time with a visual slider."],["community","Stories from the Community","Discover memories and traditions shared by people."],["passport","Heritage Passport","Collect stamps as you explore India."]];
const experienceDetails={image:["Interactive Heritage Explorer","Explore an image instead of just reading about it. Future hotspots will reveal symbols, materials, people and hidden stories."],timeline:["Timeline — See the Journey","Move through ancient roots, regional traditions, modern revival and the present day."],process:["How It’s Made","A reusable step-by-step experience for crafts, food, architecture, music and traditional practices."],connections:["Culture Connections","Discover how one tradition connects to other foods, arts, rituals, regions and communities."],surprise:["You Might Be Surprised…","Tap, look closer and uncover small facts hidden inside heritage scenes and artefacts."],quiz:["Quiz & Challenge","A common quiz engine can work across art, food, dance, architecture, textiles, instruments and festivals."],audio:["Listen & Explore","Hear the sound of living culture and learn about instruments, language, rhythm and region."],beforeafter:["Before / After","Drag between historical views and the present to understand how heritage changes over time."],community:["Stories from the Community","Real memories, local knowledge, artist stories and traditions can become part of the digital archive."],passport:["Heritage Passport","Collect virtual stamps for states, categories and heritage you have explored."]};
async function api(path,opts={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`API ${r.status}`);return r.json()}
function daySeed(){const d=new Date();return d.getFullYear()*10000+(d.getMonth()+1)*100+d.getDate()}
function dailyOrder(list,interest){const filtered=interest==="all"?list:list.filter(x=>x.interest===interest);const source=filtered.length?filtered:list;let seed=daySeed()+interest.length*97;return [...source].sort(()=>{seed=(seed*9301+49297)%233280;return seed/233280-.5})}
function Icon({children}){return <span className="nav-icon">{children}</span>}
function App(){const [page,setPage]=useState("home"),[query,setQuery]=useState(""),[items,setItems]=useState(heritage),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[posts,setPosts]=useState([]),[online,setOnline]=useState(false),[toast,setToast]=useState(""),[sidebarOpen,setSidebarOpen]=useState(false),[interest,setInterest]=useState(()=>localStorage.getItem("li-interest")||"all"),[slide,setSlide]=useState(0);
const notify=x=>{setToast(x);setTimeout(()=>setToast(""),2500)};useEffect(()=>{api("/health").then(()=>setOnline(true)).catch(()=>setOnline(false));api("/heritage").then(d=>{if(Array.isArray(d)&&d.length)setItems(d.map(x=>({...heritage.find(h=>h.id===x.id),...x,image:x.image||heritage.find(h=>h.id===x.id)?.image}))) }).catch(()=>{});api("/posts").then(setPosts).catch(()=>{})},[]);useEffect(()=>{localStorage.setItem("li-interest",interest);setSlide(0)},[interest]);const stories=useMemo(()=>dailyOrder(items,interest),[items,interest]);useEffect(()=>{if(stories.length<2)return;const t=setInterval(()=>setSlide(s=>(s+1)%stories.length),5000);return()=>clearInterval(t)},[stories]);
const search=async value=>{setQuery(value);if(!value){setItems(heritage);return}try{setItems(await api("/heritage?q="+encodeURIComponent(value)))}catch{setItems(heritage.filter(x=>(x.title+x.type+x.place+x.desc).toLowerCase().includes(value.toLowerCase())))}};const open=h=>{setSelected(h);setSidebarOpen(false)};const nav=p=>{setPage(p);setSidebarOpen(false);window.scrollTo({top:0,behavior:"smooth"})};const showExperience=id=>{setModal({type:"experience",id});setSidebarOpen(false)};
return <div className={sidebarOpen?"app sidebar-is-open":"app"}><div className="scrim" onClick={()=>setSidebarOpen(false)}></div><aside className="sidebar"><button className="brand" onClick={()=>nav("home")}><span className="brand-symbol">✺</span><span className="brand-name">LIVING <b>INDIA</b></span><small>PEOPLE · CULTURE · STORIES · FOREVER</small></button><div className="side-links"><button className={page==="home"?"active":""} onClick={()=>nav("home")}><Icon>⌂</Icon>Home</button><button className={page==="explore"?"active":""} onClick={()=>nav("explore")}><Icon>⌕</Icon>Explore</button><button className={page==="map"?"active":""} onClick={()=>nav("map")}><Icon>◈</Icon>Map</button><button className={page==="community"?"active":""} onClick={()=>nav("community")}><Icon>♧</Icon>Community</button><button onClick={()=>setModal("contribute")}><Icon>✎</Icon>Contribute</button><button className={page==="risk"?"active":""} onClick={()=>nav("risk")}><Icon>△</Icon>At Risk</button><button onClick={()=>open(heritage.find(x=>x.id==="harappa"))}><Icon>♜</Icon>Harappa</button></div><div className="side-bottom"><button><Icon>ⓘ</Icon>About</button><button onClick={()=>window.LivingIndiaAuthOpen?.("signin")}><Icon>♙</Icon>Login</button></div><div className="sidebar-note"><span>✦</span><div>OUR HERITAGE<br/><b>LIVES THROUGH YOU</b></div></div></aside>
<main className="content"><header className="topbar"><button className="burger" aria-label="Open menu" onClick={()=>setSidebarOpen(v=>!v)}><span></span><span></span><span></span></button><div className="mobile-brand">LIVING <b>INDIA</b></div><div className="search"><span>⌕</span><input value={query} onChange={e=>search(e.target.value)} placeholder="Search a heritage, art form, place, or story..."/><kbd>⌘ K</kbd></div><div className="top-actions"><span className={online?"live":"demo"}>● {online?"LIVE":"DEMO"}</span><button>♧</button><button className="avatar" onClick={()=>window.LivingIndiaAuthOpen?.("signin")}>✦</button></div></header>
{page==="home"&&<><section className="hero"><div className="hero-art"><div className="sun"></div><div className="mountains"></div><div className="temple temple-left">♜</div><div className="temple temple-right">♜</div><div className="hero-map"><div className="map-shape">INDIA</div><span className="pin p1">✦</span><span className="pin p2">✦</span><span className="pin p3">✦</span><span className="pin p4">✦</span></div><div className="map-lines"></div><div className="quote-top">“Sanskriti na kabhi purani hoti hai,<br/>na kabhi nai — woh hamesha jeevit rehti hai.”<small>— Anonymous</small></div><div className="compass">N<br/><span>✧</span><br/>S</div></div><div className="hero-copy"><div className="eyebrow">INDIA'S LIVING HERITAGE</div><h1>Discover<br/><i>Living Heritage</i></h1><h2>Stories. People. Places. A Living India.</h2><p>Explore the traditions, art forms, languages and living cultures that make India eternal.</p><div className="hero-buttons"><button className="primary" onClick={()=>nav("explore")}>Start Exploring <b>→</b></button><button className="outline" onClick={()=>setModal("contribute")}>Share a Story <b>＋</b></button></div></div><div className="hero-side"><span>EK</span><b>BHARAT</b><span>ANEK</span><b>KAHAANIYAN</b><div className="side-arrow">→</div><small>Different Stories<br/>Same Soul</small></div></section>
<section className="featured section"><div className="section-head"><div><h2>✺ Top Stories</h2><p>Freshly arranged for you · changes daily</p></div><button onClick={()=>nav("explore")}>View All →</button></div><div className="interest-tabs">{[["all","For You"],["art","Art & Craft"],["music","Music"],["performance","Performance"],["history","History"]].map(([id,label])=><button key={id} className={interest===id?"selected":""} onClick={()=>setInterest(id)}>{label}</button>)}</div><div className="carousel-window"><div className="cards carousel-track" style={{transform:`translateX(-${slide*198}px)`}}>{stories.map(h=><HeritageCard key={h.id} h={h} onClick={open}/>)}</div></div><div className="carousel-controls"><div>{stories.map((h,i)=><button key={h.id} className={i===slide?"dot active":"dot"} onClick={()=>setSlide(i)} aria-label={`Story ${i+1}`}></button>)}</div><span>Auto-playing · today’s selection</span></div></section>
<section className="experiences section"><div className="section-head"><div><h2>✦ Explore Heritage, Your Way</h2><p>Go beyond reading — listen, discover, compare and play.</p></div><button onClick={()=>showExperience("passport")}>Open Passport →</button></div><div className="experience-grid">{experienceOptions.map(([id,label,desc])=><button className="experience-card" key={id} onClick={()=>showExperience(id)}><span className="experience-icon">{({image:"▧",timeline:"◷",process:"✦",connections:"⌘",surprise:"!",quiz:"?",audio:"♪",beforeafter:"↔",community:"♧",passport:"◇"})[id]}</span><div><b>{label}</b><small>{desc}</small></div><i>→</i></button>)}</div></section><section className="map-feature section"><div className="section-head"><div><h2>✦ Explore India by State</h2><p>Every region carries a different story. Follow the glowing trail.</p></div><button onClick={()=>nav("map")}>Open Full Map →</button></div><CulturalMap items={items} onOpen={open}/></section><section className="split section"><RiskPanel onClick={()=>nav("risk")}/><Community posts={posts} onClick={()=>nav("community")}/></section><footer><span>❋ Preserve</span><span>✦ Participate</span><span>✺ Pass It On</span><b>INDIA LIVES IN ITS PEOPLE ✦</b></footer></>}
{page==="explore"&&<Explore items={items} onOpen={open}/>} {page==="risk"&&<div className="page-wrap"><div className="page-title"><div className="eyebrow">PRESERVATION</div><h1>Heritage at <i>Risk</i></h1><p>Traditions survive when people practise, teach, document and support them.</p></div><RiskPanel large/></div>} {page==="community"&&<div className="page-wrap"><div className="page-title"><div className="eyebrow">FROM THE COMMUNITY</div><h1>Stories from <i>the people</i></h1><p>Living heritage is not just history. It is what people still do, teach and remember.</p></div><Community posts={posts} large onClick={()=>{}}/></div>} {page==="map"&&<div className="page-wrap map-page"><div className="page-title"><div className="eyebrow">A CULTURAL MAP</div><h1>One India, <i>many worlds</i></h1><p>Follow the cultural trails and select a state to discover its living traditions.</p></div><CulturalMap items={items} onOpen={open} full/></div>}
</main>{selected&&<Detail h={selected} close={()=>setSelected(null)} onContribute={()=>setModal("contribute")}/>} {modal&&<Modal type={modal} close={()=>setModal(null)} notify={notify}/>} {toast&&<div className="toast">{toast}</div>}</div>}
function HeritageCard({h,onClick}){return <button className="heritage-card" onClick={()=>onClick(h)}><div className="card-img"><img src={h.image} alt=""/><span className="card-icon">{h.icon||"✦"}</span></div><div className="card-info"><h3>{h.title}</h3><p>{h.place}</p><small>{h.type}</small><span className="card-arrow">→</span></div></button>}
function RiskPanel({onClick,large}){return <div className={large?"panel risk-panel large":"panel risk-panel"}><div className="panel-head"><h2>⚠ Heritage at Risk</h2>{onClick&&<button onClick={onClick}>View All →</button>}</div>{riskItems.map(([name,desc,val,level])=><button className="risk-row" key={name} onClick={onClick}><span className={'badge '+level.toLowerCase()}>{level}</span><span className="risk-name"><b>{name}</b><small>{desc}</small></span><span className="bar"><i style={{width:val+"%"}}></i></span><em>{val}/100</em></button>)}</div>}
function Community({posts,large,onClick}){const data=posts.length?posts:[{user:"Ananya S.",text:"My grandmother still paints Madhubani at home. Here's a short story about her work...",tag:"#Madhubani",img:IMG.madhubani,likes:124},{user:"Rahul K.",text:"Visited a traditional boat making community in Kerala. The craftsmanship is incredible!",tag:"#LivingTraditions",img:IMG.harappa,likes:98}];return <div className={large?"panel community large":"panel community"}><div className="panel-head"><h2>◌ Community Voices</h2><button onClick={onClick}>Post a Story ＋</button></div>{data.slice(0,4).map((p,i)=><article className="post" key={i}><img src={p.img||IMG.madhubani} alt=""/><div><b>{p.user||"Heritage Explorer"}</b><p>{p.text||p.story}</p><small>♥ {p.likes||0}　♡ {p.comments||8}　 {p.tag||"#LivingIndia"}</small></div></article>)}</div>}
function Explore({items,onOpen}){return <div className="page-wrap"><div className="page-title"><div className="eyebrow">EXPLORE INDIA</div><h1>Stories worth <i>discovering</i></h1><p>From ancient cities to living crafts, explore the many threads of India's cultural memory.</p></div><div className="filter-row"><button className="selected">All</button><button>Art & Craft</button><button>Music</button><button>Performance</button><button>Archaeology</button></div><div className="explore-grid">{items.map(h=><HeritageCard key={h.id} h={h} onClick={onOpen}/>)}</div></div>}
function CulturalMap({items,onOpen,full}){return <div className={full?"culture-map full":"culture-map"}><div className="map-glow"></div><div className="map-paper"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/India_outline.svg" alt="India outline"/><div className="map-star star1">✦</div><div className="map-star star2">✦</div><div className="map-star star3">✦</div><div className="river river-one"></div><div className="river river-two"></div>{states.map(([name,story,x,y,type],i)=><button key={name} className={'state-pin '+type} style={{left:x+"%",top:y+"%"}} onClick={()=>onOpen(items[i%items.length])}><span className="pin-dot">✦</span><span className="pin-label"><b>{name}</b><small>{story}</small></span></button>)}</div><div className="map-legend"><span><i className="legend-dot art"></i>Art</span><span><i className="legend-dot music"></i>Music</span><span><i className="legend-dot craft"></i>Craft</span><span><i className="legend-dot performance"></i>Performance</span><span><i className="legend-dot history"></i>History</span></div><div className="map-compass">N<br/><b>✧</b><br/>S</div></div>}
function Detail({h,close,onContribute}){return <div className="detail-overlay" onClick={close}><div className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="detail-image"><img src={h.image} alt=""/><div><span>{h.type}</span><span>{h.period}</span></div></div><div className="detail-body"><div className="eyebrow">{h.place}</div><h1>{h.title}</h1><p className="lead">{h.desc}</p><div className="fact-grid">{(h.facts||[]).map(x=><div key={x}><span>✦</span>{x}</div>)}</div><div className="detail-actions"><button className="primary" onClick={onContribute}>Add your story ＋</button><button className="outline" onClick={close}>Continue exploring</button></div></div></div></div>}
function Modal({type,close,notify}){const contribute=type==="contribute";const experience=type&&type.type==="experience";if(!contribute&&!experience)return null;if(experience){const data=experienceDetails[type.id]||["Heritage Experience","This interaction is planned as part of the Living India experience layer."];return <div className="modal-overlay" onClick={close}><div className="modal feature-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">COMING TO LIVING INDIA</div><h2>{data[0]}</h2><p>{data[1]}</p><div className="feature-preview"><span>✦</span><b>Interactive module</b><small>Option added · full interaction will be implemented next</small></div><button className="primary" onClick={close}>Back to exploring →</button></div></div>};return <div className="modal-overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">COMMUNITY ARCHIVE</div><h2>Share a living story</h2><p>Your memory, craft, recipe, song or local tradition can become part of India's digital heritage.</p><form onSubmit={e=>{e.preventDefault();close();notify("Story submitted for review ✓")}}><input name="title" required placeholder="Story title"/><input name="topic" placeholder="Place or tradition"/><textarea name="story" required placeholder="Tell us the story..."/><button className="primary" type="submit">Submit for review →</button></form></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
