import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";

const heritage=[
 {id:"harappa",title:"Harappa",type:"Archaeology",icon:"🏺",place:"Punjab · Indus Valley",desc:"Urban planning, drainage, craft workshops, seals and everyday life.",risk:82},
 {id:"madhubani",title:"Madhubani Painting",type:"Craft",icon:"🖌️",place:"Bihar",desc:"A living painting tradition carried through generations of artists.",risk:46},
 {id:"baul",title:"Baul Music",type:"Oral Heritage",icon:"🎶",place:"West Bengal",desc:"Songs, philosophy and oral traditions carried by travelling musicians.",risk:68},
 {id:"kalamkari",title:"Kalamkari",type:"Textile",icon:"🧵",place:"Andhra Pradesh",desc:"Hand-painted and block-printed textile traditions with mythological motifs.",risk:39},
 {id:"theyyam",title:"Theyyam",type:"Performance",icon:"🔥",place:"Kerala",desc:"Ritual performance combining dance, music, costume and community memory.",risk:31},
 {id:"pattachitra",title:"Pattachitra",type:"Craft",icon:"🎨",place:"Odisha",desc:"Narrative cloth paintings rooted in regional storytelling.",risk:52}
];
const posts=[
 {name:"Meera Devi",role:"Practitioner",text:"In our village, the same Madhubani motif can have a different meaning depending on the occasion.",tag:"Madhubani Painting"},
 {name:"Arjun Rao",role:"Explorer",text:"Does anyone know how traditional natural dyes were prepared before synthetic colours became common?",tag:"Traditional Crafts"},
 {name:"Dr. Sen",role:"Verified Expert",text:"Regional variations are important. A tradition should not be presented as one fixed, universal practice.",tag:"Heritage Research"}
];

function App(){
 const [page,setPage]=useState("home"),[query,setQuery]=useState(""),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[postsState,setPosts]=useState(posts),[toast,setToast]=useState("");
 const filtered=heritage.filter(x=>(x.title+x.type+x.place).toLowerCase().includes(query.toLowerCase()));
 const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const addPost=(e)=>{e.preventDefault();setPosts([{name:"You",role:"New Contributor",text:e.target.story.value,tag:e.target.topic.value},...postsState]);setModal(null);notify("Contribution submitted for community review ✓")};
 return <div>
  <nav><div className="brand" onClick={()=>setPage("home")}>Living <span>India</span></div><div className="links">
   <button onClick={()=>setPage("explore")}>Explore</button><button onClick={()=>setPage("community")}>Community</button><button onClick={()=>setPage("risk")}>At Risk</button><button onClick={()=>setModal("contribute")}>Contribute</button>
  </div><button className="signin" onClick={()=>setModal("signin")}>Sign in</button></nav>

  {page==="home"&&<><section className="hero"><div><label>INDIA'S LIVING HERITAGE</label><h1>Heritage is not just <i>history.</i><br/>It is alive.</h1><p>A community-driven digital heritage platform where India's traditions, stories and living knowledge are discovered, contributed, discussed and preserved.</p><div className="actions"><button className="primary" onClick={()=>setPage("explore")}>Explore India →</button><button onClick={()=>setModal("contribute")}>Share a story</button></div><div className="stats"><b>2,480+<small>heritage records</small></b><b>614<small>community voices</small></b><b>126<small>practitioners</small></b></div></div><div className="hero-art"><div className="sun"></div><div className="temple">◒</div><div className="arttext">LIVING<br/><strong>INDIA</strong></div></div></section>
  <section><div className="eyebrow">WHY LIVING INDIA?</div><h2>From static information to <em>living knowledge.</em></h2><div className="featuregrid">{[["🧑‍🎨","Community Voices","Let practitioners and families preserve stories in their own words."],["✓","Verification","Separate community memories, practitioner knowledge and expert-reviewed claims."],["🎙️","Oral Heritage","Capture regional-language stories through voice instead of requiring people to type."],["🚨","Heritage at Risk","Identify traditions that need documentation, participation or preservation support."]].map(f=><article><span>{f[0]}</span><h3>{f[1]}</h3><p>{f[2]}</p></article>)}</div></section>
  <section className="dark"><div className="eyebrow gold">EXPERIENCE</div><h2>Don't just read history. <em>Step inside it.</em></h2><div className="experience"><div><span className="tag">INTERACTIVE MODULE</span><h3>🏺 Experience Harappa</h3><p>Explore a reconstructed 2D Harappan settlement, learn through quests and discover how urban life worked.</p><button className="goldbtn" onClick={()=>{setPage("explore");setSelected(heritage[0])}}>Launch experience →</button></div><div className="mini-map"><span>H</span><span>⌂</span><span>▦</span><span>⚓</span></div></div></section></>}

  {page==="explore"&&<main className="page"><div className="eyebrow">DISCOVER</div><h1>Explore India's heritage</h1><p className="lead">Find traditions, places and stories — then follow the people who keep them alive.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search crafts, festivals, places…"/></div><div className="chips"><button>All</button><button>Crafts</button><button>Oral heritage</button><button>Archaeology</button><button>Performance</button></div><div className="grid">{filtered.map(x=><article className="heritage" onClick={()=>setSelected(x)}><div className="hicon">{x.icon}</div><span className="tag">{x.type}</span><h3>{x.title}</h3><small>{x.place}</small><p>{x.desc}</p><button>Explore →</button></article>)}</div></main>}

  {page==="community"&&<main className="page"><div className="eyebrow">COMMUNITY VOICES</div><h1>Culture belongs to everyone.</h1><p className="lead">Ask questions, share regional variations and learn directly from people connected to the tradition.</p><button className="primary" onClick={()=>setModal("contribute")}>+ Share your heritage</button><div className="feed">{postsState.map(p=><article className="post"><div className="avatar">{p.name[0]}</div><div><div><b>{p.name}</b> <span className="role">{p.role}</span></div><p>{p.text}</p><span className="tag">{p.tag}</span><div className="postactions"><button onClick={()=>notify("Saved to your heritage collection")}>♡ Save</button><button onClick={()=>notify("Reply editor opened")}>↩ Reply</button><button onClick={()=>notify("Thank you for helping moderate the community")}>⚑ Report</button></div></div></article>)}</div></main>}

  {page==="risk"&&<main className="page"><div className="eyebrow">PRESERVE</div><h1>Heritage at risk</h1><p className="lead">A prototype vitality index highlights traditions that may need greater documentation, participation or community support.</p><div className="riskintro"><div><strong>126</strong><span>traditions tracked</span></div><div><strong>18</strong><span>high priority</span></div><div><strong>47</strong><span>need documentation</span></div></div><div className="risklist">{heritage.sort((a,b)=>b.risk-a.risk).map(x=><article><div className="rhead"><span>{x.icon} <b>{x.title}</b></span><strong>{x.risk}/100</strong></div><small>{x.place} · {x.type}</small><div className="meter"><i style={{width:x.risk+"%"}}></i></div><p>{x.risk>70?"High priority: limited documentation or participation signals." : x.risk>50?"Watch: stronger documentation and youth participation could help.":"Stable: continue community documentation and learning."}</p></article>)}</div></main>}

  {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><div className="bigicon">{selected.icon}</div><span className="tag">{selected.type}</span><h2>{selected.title}</h2><small>{selected.place}</small><p>{selected.desc}</p><h3>Heritage DNA</h3><div className="dna"><span>Origin</span><span>Technique</span><span>Stories</span><span>Practitioners</span><span>Regional variations</span><span>Sources</span></div><h3>Community voices</h3><p>🧑‍🎨 <b>Practitioner verified</b> · 14 contributions</p><button className="primary" onClick={()=>notify("Interactive heritage experience queued")}>{selected.id==="harappa"?"Launch 2D experience →":"Explore this tradition →"}</button></div></div>}

  {modal&&<div className="overlay" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(null)}>×</button>{modal==="contribute"?<><div className="eyebrow">CONTRIBUTE</div><h2>Preserve a living story.</h2><p>Share knowledge from your family, community or practice. New contributions enter a review queue.</p><form onSubmit={addPost}><label>Topic</label><input name="topic" required placeholder="e.g. Baul Music"/><label>Your story</label><textarea name="story" required rows="6" placeholder="Tell us what you know…"></textarea><label>Source type</label><select><option>My own/community knowledge</option><option>Practitioner knowledge</option><option>Family archive</option></select><button className="primary">Submit for review →</button></form></>:<><div className="eyebrow">MEMBER ACCESS</div><h2>Welcome back.</h2><label>Email</label><input placeholder="you@example.com"/><label>Password</label><input type="password" placeholder="••••••••"/><button className="primary" onClick={()=>{setModal(null);notify("Signed in to prototype")}}>Sign in</button></>}</div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);
